---
federated:
  hosts:
    ip-11-0-1-001.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq2
        scheme: tcp
        address: ip-11-0-2-002.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-3-003.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq1-federation
          upstreams:
            - name: amq2
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq2
            - name: amq3
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq3
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
    ip-11-0-2-002.eu-west-2.compute.internal:
      amq_broker_instance_name: amq2
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-2-002.eu-west-2.compute.internal
        port: 61616
      - name: amq1
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-3-003.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq2-federation
          upstreams:
            - name: amq1
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq1
            - name: amq3
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq3
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
    ip-11-0-3-003.eu-west-2.compute.internal:
      amq_broker_instance_name: amq3
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-3-003.eu-west-2.compute.internal
        port: 61616
      - name: amq1
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq2
        scheme: tcp
        address: ip-11-0-2-002.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq3-federation
          upstreams:
            - name: amq1
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq1
            - name: amq2
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq2
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
