---
- name: Test AMQ custom installation
  hosts: localhost
  vars:
    ansible_ssh_private_key_file: my_keypair.pem
    artemis_bin: "amq-broker/apache-artemis-2.33.0.redhat-00010/bin/artemis"
  tasks:
    - name: Get AMQ nodes info
      amazon.aws.ec2_instance_info:
        region: "eu-west-2"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          instance-state-name: ["running"]
          "tag:Name": "amq*"
      register: amq_nodes

    - name: Create private_dns_names
      ansible.builtin.set_fact:
        private_dns_names: []

    - name: Set AMQ nodes private_dns_names
      ansible.builtin.set_fact:
        private_dns_names: "{{ private_dns_names + [{'name': item.tags.Name, 'dns': item.network_interfaces[0].private_dns_name}] }}"
      loop: "{{ amq_nodes.instances }}"

    - name: Ensures /home/ec2-user/amq-broker exists
      ansible.builtin.file:
        path: /home/ec2-user/amq-broker
        mode: "0755"
        state: directory

    - name: Extract amq-broker-bin.zip
      ansible.builtin.unarchive:
        src: amq-broker-7.12.0-bin.zip
        dest: /home/ec2-user/amq-broker
        mode: "0755"

    - name: Start consumer
      ansible.builtin.command: "{{ artemis_bin }} consumer --user amq-broker --password amq-broker --message-count 200 --url tcp://{{ item.dns }}:61616"
      poll: 0
      async: 60
      loop: "{{ private_dns_names | selectattr('name', 'equalto', 'amq1') }}"
      changed_when: false
      register: amq1_consumer

    - name: Start producer
      ansible.builtin.command: "{{ artemis_bin }} producer --user amq-broker --password amq-broker --message-count 600 --url tcp://{{ item.dns }}:61616"
      loop: "{{ private_dns_names | selectattr('name', 'equalto', 'amq1') }}"
      changed_when: false
      register: amq1_producer

    - name: Wait for consumers to end
      ansible.builtin.async_status:
        jid: "{{ item.results[0].ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 5
      delay: 10
      loop:
        - "{{ amq1_consumer }}"
