---
all:
  hosts:
    ip-11-0-1-01.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
    ip-11-0-1-02.eu-west-2.compute.internal:
      amq_broker_instance_name: amq2
    ip-11-0-1-03.eu-west-2.compute.internal:
      amq_broker_instance_name: amq3
single:
  hosts:
    ip-11-0-1-01.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
dual:
  hosts:
    ip-11-0-1-01.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
      activemq_ha_role: master
    ip-11-0-1-02.eu-west-2.compute.internal:
      amq_broker_instance_name: amq2
      activemq_ha_role: slave
