---
- name: Create AWS infrastructure
  hosts: localhost
  gather_facts: false
  vars:
    # https://eu-west-2.console.aws.amazon.com/ec2/home?region=eu-west-2#AMICatalog:
    create_vpc_image_id: "ami-016bc0ffc60455bdf"
  roles:
    - name: "Creating VPC"
      role: "create_vpc"

- name: Configure bootstrap box
  hosts: bootstrap
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: roles/configure_bootstrap/files/my_keypair.pem
  environment:
    ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: "{{ ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN }}"
  roles:
    - name: "Configure bootstrap"
      role: "configure_bootstrap"
