---
- name: Create AWS infrastructure
  hosts: localhost
  gather_facts: true
  vars:
    # https://eu-west-2.console.aws.amazon.com/ec2/home?region=eu-west-2#AMICatalog:
    create_vpc_image_id: "ami-0727cf12519cc2b5b"
  environment:
    SSH_KEY_VAULT_PASS: "{{ SSH_KEY_VAULT_PASS }}"
  roles:
    - name: "Creating VPC"
      role: "create_vpc"

# Python 3.9 comes with the AMIs, we need 3.11 so needs to be included before being used in the configure_bootstrap role
- name: Configure python on host boxes
  hosts: all
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/roles/configure_bootstrap/files/ec2_keypair.pem"
  roles:
    - name: "Configure hosts with latest python"
      role: "configure_hosts"
  tags:
    - blank

- name: Configure bootstrap box
  hosts: bootstrap
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/roles/configure_bootstrap/files/ec2_keypair.pem"
  environment:
    ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: "{{ ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN }}"
  roles:
    - name: "Configure bootstrap"
      role: "configure_bootstrap"
  tags:
    - blank
