---
- name: Deploy AMQ in 3 broker clustered setup
  hosts: clustered
  gather_facts: true
  vars:
    # SSH key
    ansible_ssh_private_key_file: ec2_keypair.pem
    # Clustering
    amq_broker_cluster_enabled: true
    amq_broker_cluster_discovery: "provided"
    # HACK: Allows console
    amq_broker_cors_strict_checking: false
    # Basic config
    amq_broker_addresses:
      - name: TEST
        anycast:
          - name: TEST
    amq_broker_acceptors:
      - name: artemis
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port }}"
        parameters:
          protocols: CORE
      - name: amqp
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port_amqp }}"
        parameters:
          protocols: AMQP
  roles:
    - redhat.amq_broker.amq_broker
