---
- name: Test AMQ master/slave installation
  hosts: localhost
  gather_facts: false
  vars:
    # SSH key
    ansible_ssh_private_key_file: ec2_keypair.pem
  roles:
    - test_amq
  tasks:
    ## Scenario:
    # Start a producer on AMQ1 (primary), stop AMQ1 which should cause AMQ2 (backup) to start up. Attach consumer to AMQ2
    # Consumer on AMQ2 should get 200 messages, if it does not, test fails

    - name: Start producer on amq1
      ansible.builtin.command: "{{ artemis_bin }} producer {{ test_amq_producer_args }} --url tcp://{{ item.dns }}:61616"
      loop: "{{ private_dns_names | selectattr('name', 'equalto', 'amq1') }}"
      changed_when: false

    - name: Stop amq1 system.d service
      delegate_to: amq1
      become: true
      throttle: 1
      ansible.builtin.systemd_service:
        name: "amq1"
        state: stopped

    - name: Start consumer on amq2
      ansible.builtin.command: "{{ artemis_bin }} consumer {{ test_amq_consumer_args }} --url tcp://{{ item.dns }}:61616"
      loop: "{{ private_dns_names | selectattr('name', 'equalto', 'amq2') }}"
      changed_when: false
