---
- name: Test AMQ custom installation
  hosts: localhost
  gather_facts: false
  roles:
    - test_amq
  tasks:
    ## Scenario:
    # Single consumer and producer
    # Consumer should get 200 messages, if it does not, test fails

    - name: Set DNSs
      ansible.builtin.set_fact:
        amq1: "{{ private_dns_names | selectattr('name', 'equalto', 'amq1') | first }}"

    - name: Start consumer
      ansible.builtin.command: "{{ artemis_bin }} consumer {{ test_amq_consumer_args }} --url tcp://{{ amq1.dns }}:61616"
      poll: 0
      async: 60
      changed_when: false
      register: amq1_consumer

    - name: Start producer
      ansible.builtin.command: "{{ artemis_bin }} producer {{ test_amq_producer_args }} --url tcp://{{ amq1.dns }}:61616"
      changed_when: false

    - name: Wait for consumers to end
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 5
      delay: 10
      loop:
        - "{{ amq1_consumer }}"
